### ISSUE TITLE
Episode 02-index-slice-subset

### ISSUE THREAD

**Issue by brendam** [LibraryCarpentry/library-python#11]
I'm not sure what the second last challenge is meant to do:

> Create a new DataFrame that only contains observations with Language values that are English or French. Assign each language value in the new DataFrame to a new value of x. Determine the number of null values in the subset.

What does "Assign each language value in the new DataFrame to a new value of x" mean?

**Comment by mkuzak** [comment]
@c-martinez can you comment on that?

**Comment by c-martinez** [comment]
The [original challenge](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/02-index-slice-subset.md#challenges-1), _Assign each sex value in the new DataFrame to a new value of 'x'_. As I understand it, the spirit of the original challenge is to be able to determine how many males, females and undecided there are in the data set.

For the library lesson, I don't think there are any _undecided_ languages, so I was not very sure what should the challenge aim for. Perhaps just the number of articles for each language? In either case, this should be rephrased.

**Comment by c-martinez** [comment]
Just updated the challenges. @brendam, do you think they are better this way?

**Comment by brendam** [comment]
yes, that looks like it will work, thanks.

**Comment by mkuzak** [comment]
solved by c12318ac31070ad8a2a7b26ca26bfb5a7ef31645
