### ISSUE TITLE
Need to update setup.md with correct instructions for this workshop

### ISSUE THREAD

**Issue by brendam** [LibraryCarpentry/library-python#17]
Currently the instructions are for how to build new lessons, not for this workshop.

**Comment by brendam** [comment]
The [Leeds workshop install instructions](https://arcleeds.github.io/2016-11-21-leeds/install.html) might be useful?

**Comment by mkuzak** [comment]
@brendam can you confirm that this is ok now and close the issue if you agree with the solution?

**Comment by brendam** [comment]
content is good, but something strange is happening during build - the included files are having some html changed to text:

`Select "SQLite Manager" from the "Tools" menu and it will open within Firefox </ul> </ol> </div>`

so page layout is wrong

**Comment by mkuzak** [comment]
@c-martinez @brendam this is rendered incorrectly but also the content is not what it should be. This is the setup for the workshop not for the lesson. Python lesson should not include instructions for other tools.
