### ISSUE TITLE
Inline code isn't being highlighted fully (on my computer)

### ISSUE THREAD

**Issue by brendam** [LibraryCarpentry/library-python#5]
This is what it looks like in the ecology lesson: 
<img width="985" alt="ecology-lesson" src="https://cloud.githubusercontent.com/assets/247237/19415107/69447586-93a8-11e6-8b2e-4c06a3e1f582.png">

and this is what I'm seeing locally (might just be a difference with Github rendering vs local)

<img width="851" alt="library-python" src="https://cloud.githubusercontent.com/assets/247237/19415110/aeabe686-93a8-11e6-8502-b36df87f02c3.png">

Without the bounding box it is hard to distinguish the `=` as code.

**Comment by brendam** [comment]
Not being highlighted on github either

**Comment by mkuzak** [comment]
This is how the styling works in new template. You can see it in other Software Carpentry lessons using new template. DC Python lesson uses old template.

**Comment by brendam** [comment]
@mkuzak the software carpentry lesson example seems to have inline code with a light gray background, where our one is just showing a fixed face font - can you please check? I think the current highlighting is too minimal, needs to be a bit clearer what is code and what is text.

**Comment by mkuzak** [comment]
@brendam can you point me to example of it in software carpentry lesson?

**Comment by brendam** [comment]
ok, now I feel like I was seeing things. Was sure I saw some pale gray background this morning, not seeing it now. So you are right, we seem to be using the default - where should I discuss whether that default is good?

**Comment by mkuzak** [comment]
That's ok, I do agree grey background makes it more stand out, but that's what we get. If you want it to be changed in LC only I'd mention it at gitter chat, otherwise (SC/DC wide) on software carpentry discussion mailing list.
