### ISSUE TITLE
ISSN field has multiple values

### ISSUE THREAD

**Issue by brendam** [LibraryCarpentry/library-python#7]
In 01-starting-with-data we work with the ISSN field as if it has single values, but some of the items have multiple values separated by `|` - so the numbers we are getting will not be correct. This is shown in the output in "Did you get #3 right?"

Perhaps this is cleaned up in a later lesson?

**Comment by c-martinez** [comment]
We are not cleaning the ISSN values. I don't think the numbers are incorrect because the ISSN's which appear as a pair do not appear elsewhere. E.g. `0367-0449|1988-3250` appear only as a pair, and never `0367-0449` or `1988-3250` on their own. So not a real problem, is it?

**Comment by brendam** [comment]
No, I don't think it is a problem, just wanted to note it.
