### ISSUE TITLE
challenge numbered lists not numbering properly

### ISSUE THREAD

**Issue by brendam** [LibraryCarpentry/library-python#8]
The numbering in one of the challenges goes 1, 2, 1 and then we ask if '3' worked.

**Comment by brendam** [comment]
I think this might be because they have source blocks in them?

**Comment by mkuzak** [comment]
@brendam can you check if this is ok now and close the issues if you're happy with the solution?

**Comment by brendam** [comment]
that works - I've raised an issue with the template project.
